### PR TITLE
Wiki update (part 1)

### PR DESCRIPTION
**Pull request by AntonnMal**

### CODE REVIEW

**Comment by dgibbs64** [comment]
Wow someone has been busy. Thanks for this :)

**Comment by AntonnMal** [comment]
I'm not done yet

**Comment by dgibbs64** [comment]
I got that vibe with (part 1) haha

**Comment by dgibbs64** [comment]
brilliant improvements here. Thanks for taking the time to improve the docs 🥇

**Comment by AntonnMal** [comment]
No problem.

**Pull request merged**
